### ISSUE TITLE
Same broken irc-voice.svg links in icon folder every time I update the icon theme.

### ISSUE THREAD

**Issue by freefreeno** [cbrnix/Newaita#98]
This may be intended but just to let you know that every time I update the icons i have these broken links in my icon folder. Here is the screenshot. Also some more links broken in there too.
Same every time.

![Screenshot_20190506_163030](https://user-images.githubusercontent.com/41884680/57256407-31e50a80-701c-11e9-8d87-e1e6fa50e5fd.png)

**Comment by cbrnix** [comment]
Fixed

**Comment by freefreeno** [comment]
Well thank you very much.

**Comment by freefreeno** [comment]
I just installed the new ones and fixed my script for the newaita-b icons and that is fine but I am still seeing these when searching for broken links. I am not sure what this means but it is not the same as broken link for sure.

![Screenshot_20190520_150248](https://user-images.githubusercontent.com/41884680/58048466-696daf80-7b10-11e9-80b6-35234587e266.png)

**Comment by cbrnix** [comment]
Wrong links. Fixed

**Comment by freefreeno** [comment]
Thanks again.

**Comment by freefreeno** [comment]
Just commenting here so that i don't create a new issue. Do you think sometime in the future we maybe could get some darker blue icons.

**Comment by cbrnix** [comment]
> Just commenting here so that i don't create a new issue. Do you think sometime in the future we maybe could get some darker blue icons.

Now I have two requests (also for red ones). The theme of icons increases exponentially. I probably will do it just as with special ones - a separate archive of a number of other colors.

**Comment by freefreeno** [comment]
Yes thank you. Also some people that are less inclined to even try to change the color of your icons say that it is hard lol. I add all of them into one big folder and if I don't like any of them I just remove them and then fix the script. Maybe something similar to the old Adwaita dark blue that was used for selected backgrounds.

**Comment by freefreeno** [comment]
In case you were wondering I am working with #29508f but of course there your fonts and you how to make them look good but just throwing that out there. I am about to release a lot of themes with your your icons as guide for the colors but it is a dark theme and the blue is giving me fits because it is light and it is hard to explain but some colors just are hard to make work. In KDE you not only have to have the one selected background color you also have to use the shades of that same color for a lot of other things.

**Comment by freefreeno** [comment]
I have another idea that could really help me when trying to match colors. Instead of you having to make complete icon themes with different colors how about just add a folder with different color desktop folder icons for the default Newaita icons. The default icons are very nice indeed and I tend to like the brown because it is neutral but the purple desktop folder takes the neutrality away from the icon set and makes it hard to match because of that one icon but if we had different desktop folder colors so we can remove the purple one and add the color of our theme desktop folder then that would make those icon the most durable icon set in the Linux world for sure. it would make it where we could use the default icons with any color in the world and I think that would be awesome because I ONLY USE YOUR ICONS. I ran into this problem this morning working on a theme that does not have a match in your icon set and the defaults are the best so far but if I had one single desktop folder icon then that would make it match perfectly and would do so for any others too. Just an idea. Thanks

**Comment by cbrnix** [comment]
Josh, I would like to do something different. Some kind of graphical menu in which you could choose the desired color. After selecting the desired icons were downloaded from the server (say, GIt) and replaced.
But unfortunately, my programming knowledge is like a snail XD. True, this would have the disadvantage of binding to the network.

**Comment by freefreeno** [comment]
I also am not good at any programming and sounds like your in the same situation as I am with learning svg's. I love UI design and I need so badly to learn QT and I need to become a pro at inkscape worse than anything in the world. It is keeping from making some decent money doing stuff I love but I find myself putting it off and I need to stopping patching things to together and just learn the stuff already. " Not to say that that what your doing". Your icons are the best I have ever used for sure and I am so picky when it comes to icons and well the whole operating system. Just think If I could learn all my stuff and then put it out with your icons well like I have said before I try to get people to use your icons for sure but people are reluctant to open that terminal. Basically if i don't learn svg and I mean learn to do anything with svg then I might as well stop even trying. I don't even know where to begin. i want to make simple stuff at first like say the kickoff menu in KDE Plasma with the search box in it and design stuff like all kinds of widgets. I am telling you there is some decent side money to be had doing that stuff. There is this little thing called " dialog" in Arch Linux and what it does is offer simple UI for selecting stuff. it is used in the wifi-menu when installing Arch Linux and I think you could use it also. I am a person that never EVER used even a windows PC until my 30's but when I got started I loved it and then I got tired of being trapped in a box so to say and came to Linux and I have made way to Arch linux and that is where I will stay. I think I have taught myself pretty good but it is hard when I have no one to ask questions to and you know I have to search for things that I don't even know what I am searching for. Anyways I am stuck on svg's for now and trying to work with Inkscape. I really think your icons would be number 1 if you did have that menu.

**Comment by cbrnix** [comment]
> @cbrnix I am sorry for bothering you but all the icons I can find can you believe there has no one made a match for Materia-kde theme. The selected background color is #3b5074.. I have made a new Materia Grey theme and as you know my first theme was modeled after your icons and I am about to release the new theme and would love to use your icons. It use the color above for the selected background color also. my first theme was the Materia Manjaro theme named from your icons. As you know that is pretty dark and it doesn't have to be an exact match but maybe the little part in the center could have that color. I love your icons. I tried to use Papirus the other day and yea well that lasted a whole ten min.

Sorry for the long silence. You yourself see how many desires people have, and time does not stretch. Do you still need these icons? I can create a separate theme with these, if necessary (XD exclusive)

**Comment by freefreeno** [comment]
@cbrnix No I do not but I really appreciate you taking the time to answer me. Great to here from you by the way. Your icons are still great and I still use them but i have fell behind in my work or my hobby and I am really trying to play catch up on learning my stuff so I create a KDE from the ground up by myself. I have been scolded on the KDE site for using others work too much and so I have learn I guess. What I wish we could do there is no way possible to split the plings so it will not work. What would be cool is for you to make plasma icons and put them on the site like a normal icon set. Tell people what they are and I promise people will use them. Give me first shot at them and I will add them to my Materia Manjaro theme or to another theme and then I will be only one step from having a theme away from the original Materia. Here is the bad thing about what I ask. You know I can add stuff as dependency to a KDE look and feel but i don't think we can do that with plasma icons so it would not really be fair to you. Although I am sure you will get a ton of downloads and it is a great idea for you if I used them in my theme I believe I would have to include them like they were mine in my theme since it will not pull in plasma icons. So see I have a great idea for you but it just doesn't work out right. It is about 20 to 30 icons in the plasma part of the KDE theme. Even if you don't let me use them in a theme I can still use them and more people will too. I suggest looking inside the Materia plasma theme and you will see the icons required and also look inside the breeze plasma theme.

**Comment by cbrnix** [comment]
@freefreeno

Do you have other means of communication (Telegram, for example?), We could adjust the work on the plasma topic. I can make them, just better know the concept of icons. You just add them to the topic and that’s it. I guess it’s difficult to create a plasma theme (I tried somehow, but I didn’t have enough patience). Just in case I will leave an e-mail
ghostdmn2@gmail.com

**Comment by cbrnix** [comment]
I tried audio. It seems to work correctly
https://drive.google.com/open?id=1s-KdLaFYi1iKfWc9PH3xlxOX_vqXFchW

**Comment by freefreeno** [comment]
Well I haven't ever used telegram but I can and I would love to work on something. if you can bare with m,e I am in the middle of updating a theme this afternoon and my internet is screwed so yea problems. If you will leave me the info on how to contact you I will asap I promise.

**Comment by freefreeno** [comment]
https://github.com/PapirusDevelopmentTeam/materia-kde

Go here and clone this. Look into plasma desktoptheme folder and you will see what you have to have and what will work.

**Comment by freefreeno** [comment]
Yes the audio does work. You don't have to do it this way but to me it looks better if you make white on the panel but in the tooltip and the little pop up menu it is colored. Well this is where you will want two sets. A complete mono set and a colored set. Colored as in not colored on the panel but like when you hit your volume keyboard button it pops up the little menu and it would be colored there and colored the same color in the tooltip for the icon but mono while setting in the panel.

**Comment by freefreeno** [comment]
@cbrnix I am gonna download and install telegram today and I will leave my info here. I would love to work with ya on something for a nice plasma theme. I believe your style might do better with say a flat theme BUT the most downloads would come from gradient icons for your kickoff menu and log and out screen. Look at sweet for ideas on this. I already have colors in mind I like. 
I am gonna try to do a kind mix of both worlds with this. A flat dark theme with gradient icons in the kickoff menu. There is really only 4 styles of these icons out there. You have mono vs colored. You also have flat single color vs  gradient. Only two themes to show you best of both worlds would materia-kde and sweet. I think you will make some really cool ones.

**Comment by cbrnix** [comment]
@ freefreeno 
In two days I will have a weekend, there it will be possible to discuss. Moreover, I have a few drafts of new topics. While setting up Telegram, then we will discuss what and how to do

**Comment by freefreeno** [comment]
Have you ever used the telegram qt. I am on KDE

**Comment by cbrnix** [comment]
> Have you ever used the telegram qt? I am on KDE

This, in my opinion, is not even Gui. Library set. Put the usual

**Comment by freefreeno** [comment]
@cbrnix I have it installed and activated now but no idea what to do next.

**Comment by freefreeno** [comment]
@cbrnix How do I find you on telegram. I am on there now. Josh Freeno

**Comment by cbrnix** [comment]
In the settings you must have a user nickname.  Throw it off, or the number to which you registered.  Email me at ghostdmn2@gmail.com
